print("aj tkinter")
from tkinter import *
####
##tk= Tk()
##tk.geometry("950x630")
####Text.configure(font=("Times New Roman", 20, "italic"))
####(tkt,justify="center",command=, text = "", fg = "", padx="",pady="",bd="").place(x=30, y=50)
##def mainpage():
##      tk.title("STUDENT SURFACE")
##      tk.geometry("950x630")
##      redbutton = Button(tk,justify="center",command=loginclicked, text = "LOGIN", fg = "red", padx="10",pady="10",bd="1",font=("Times New Roman", 25, ""))
##      redbutton.place(x = 810,y=0)
##      name.destroy()
##      email.destroy()
##def loginclicked():
##      tk.geometry("950x630")
####      tk.geometry("400x250")  
##      name = Label(tk, text = "Name").place(x = 30,y = 50)  
##      email = Label(tk, text = "Email").place(x = 30, y = 75)  
##      password = Label(tk, text = "Password").place(x = 30, y = 100)  
##      e1 = Entry(tk).place(x = 80, y = 50)  
##      e2 = Entry(tk).place(x = 80, y = 75)  
##      e3 = Entry(tk).place(x = 95, y = 100)
####      submit = Button(tk, text = "Submit", command=mainpage).place(x = 30, y = 130)
##      submit = Button(tk,justify="center",command=mainpage, text = "submit", fg = "blue", padx="4",pady="4",bd="2",font=("Times New Roman", 25, "")).place(x = 30, y = 130)
##      redbutton.destroy()
##mainpage()
messageWindow= Tk()
messageWindow.title("İstanbul")
messageWindow.geometry("400x600")
##messageWindow.resizable(width=False,height=False)
frame1 = Frame(messageWindow, width =400, height=100)
frame1.pack(side=TOP, expand= True, fill=BOTH)
frame2 = Frame(messageWindow, width =400, height=500)
frame2.pack(side=TOP, expand= True, fill=BOTH)
def dd():
      nframe44 = Frame(messageWindow, width =400, height=100)
def goSearchBarButton():
      
      searchbarFrame.place(x=0,y=0)
      nframe1 = Frame(searchbarFrame, width =400, height=100)
      nframe1.pack(side=TOP, expand= True, fill=BOTH)
      nframe2 = Frame(searchbarFrame, width =400, height=500, background="black")
      nframe2.pack(side=TOP, expand= True, fill=BOTH)
      button = Button(searchbarFrame, width =400, height=500, background="black",command=dd)
goSearchBarButton()
messageWindow.mainloop()
